id: P1A11694D
initial_creation_type: ocr
source_metadata:
  volumes:
    c8aa75310cde447895e8f056237d03ff:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ཚ་ཚ་གདབ་པའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
